gnome-terminal -- bash -c "cd /home/amit/IdeaProjects/ecommerce-saga-poc/gateway-service && mvn spring-boot:run"
gnome-terminal -- bash -c "cd /home/amit/IdeaProjects/ecommerce-saga-poc/product-service && mvn spring-boot:run"
gnome-terminal -- bash -c "cd /home/amit/IdeaProjects/ecommerce-saga-poc/user-service && mvn spring-boot:run"
gnome-terminal -- bash -c "cd /home/amit/IdeaProjects/ecommerce-saga-poc/order-service && mvn spring-boot:run"
gnome-terminal -- bash -c "cd /home/amit/IdeaProjects/ecommerce-saga-poc/catalog-service && mvn spring-boot:run"
gnome-terminal -- bash -c "cd /home/amit/IdeaProjects/ecommerce-saga-poc/payment-service && mvn spring-boot:run"
gnome-terminal -- bash -c "cd /home/amit/IdeaProjects/ecommerce-saga-poc/event-log-service && mvn spring-boot:run"
gnome-terminal -- bash -c "cd /home/amit/IdeaProjects/ecommerce-saga-poc/shipping-service && mvn spring-boot:run"