version: "3.8"

services:
  ecommerce-rmq:
    image: rabbitmq:management-alpine
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - mynet

  gateway-service:
    image: ecommerce-saga-poc/gateway-service
    ports:
      - "8000:8000"
    environment:
      - SERVER_PORT=8000
      - PRODUCT_SERVICE_URL=http://product-service:8081
      - CATALOG_SERVICE_URL=http://catalog-service:8084
      - ORDER_SERVICE_URL=http://order-service:8083
      - USER_SERVICE_URL=http://user-service:8082
      - SHIPPING_SERVICE_URL=http://shipping-service:8087
      - PAYMENT_SERVICE_URL=http://payment-service:8085
    networks:
      - mynet
    depends_on:
      - ecommerce-rmq

  product-service:
    image: ecommerce-saga-poc/product-service
    ports:
      - "8081:8081"
    environment:
      - SERVER_PORT=8081
      - MQ_USERNAME=guest
      - MQ_PASSWORD=guest
      - MQ_HOST=ecommerce-rmq
      - MQ_VHOST=/
      - MQ_PORT=5672
      - GATEWAY_URL=http://gateway-service:8000
      - JWT_SECRET=TWFwPFN0cmluZywgT2JqZWN0PiBjbGFpbXMgPSBuZXcgSGFzaE1hcDw+KCk7CmNsYWltcy5wdXQoImEiICwgMSk7CmNsYWltcy5wdXQoImIiICwgMik7Cg==
    networks:
      - mynet
    depends_on:
      - ecommerce-rmq

  user-service:
    image: ecommerce-saga-poc/user-service
    ports:
      - "8082:8082"
    environment:
      - SERVER_PORT=8082
      - MQ_USERNAME=guest
      - MQ_PASSWORD=guest
      - MQ_HOST=ecommerce-rmq
      - MQ_VHOST=/
      - MQ_PORT=5672
      - GATEWAY_URL=http://gateway-service:8000
      - JWT_SECRET=TWFwPFN0cmluZywgT2JqZWN0PiBjbGFpbXMgPSBuZXcgSGFzaE1hcDw+KCk7CmNsYWltcy5wdXQoImEiICwgMSk7CmNsYWltcy5wdXQoImIiICwgMik7Cg==
    networks:
      - mynet
    depends_on:
      - ecommerce-rmq

  order-service:
    image: ecommerce-saga-poc/order-service
    ports:
      - "8083:8083"
    environment:
      - SERVER_PORT=8083
      - MQ_USERNAME=guest
      - MQ_PASSWORD=guest
      - MQ_HOST=ecommerce-rmq
      - MQ_VHOST=/
      - MQ_PORT=5672
      - GATEWAY_URL=http://gateway-service:8000
      - JWT_SECRET=TWFwPFN0cmluZywgT2JqZWN0PiBjbGFpbXMgPSBuZXcgSGFzaE1hcDw+KCk7CmNsYWltcy5wdXQoImEiICwgMSk7CmNsYWltcy5wdXQoImIiICwgMik7Cg==
    networks:
      - mynet
    depends_on:
      - ecommerce-rmq

  catalog-service:
    image: ecommerce-saga-poc/catalog-service
    ports:
      - "8084:8084"
    environment:
      - SERVER_PORT=8084
      - MQ_USERNAME=guest
      - MQ_PASSWORD=guest
      - MQ_HOST=ecommerce-rmq
      - MQ_VHOST=/
      - MQ_PORT=5672
      - GATEWAY_URL=http://gateway-service:8000
      - JWT_SECRET=TWFwPFN0cmluZywgT2JqZWN0PiBjbGFpbXMgPSBuZXcgSGFzaE1hcDw+KCk7CmNsYWltcy5wdXQoImEiICwgMSk7CmNsYWltcy5wdXQoImIiICwgMik7Cg==
    networks:
      - mynet
    depends_on:
      - ecommerce-rmq

  payment-service:
    image: ecommerce-saga-poc/payment-service
    ports:
      - "8085:8085"
    environment:
      - SERVER_PORT=8085
      - MQ_USERNAME=guest
      - MQ_PASSWORD=guest
      - MQ_HOST=ecommerce-rmq
      - MQ_VHOST=/
      - MQ_PORT=5672
      - GATEWAY_URL=http://gateway-service:8000
      - JWT_SECRET=TWFwPFN0cmluZywgT2JqZWN0PiBjbGFpbXMgPSBuZXcgSGFzaE1hcDw+KCk7CmNsYWltcy5wdXQoImEiICwgMSk7CmNsYWltcy5wdXQoImIiICwgMik7Cg==
    networks:
      - mynet
    depends_on:
      - ecommerce-rmq

  event-log-service:
    image: ecommerce-saga-poc/event-log-service
    ports:
      - "8086:8086"
    environment:
      - SERVER_PORT=8086
      - MQ_USERNAME=guest
      - MQ_PASSWORD=guest
      - MQ_HOST=ecommerce-rmq
      - MQ_VHOST=/
      - MQ_PORT=5672
      - GATEWAY_URL=http://gateway-service:8000
      - JWT_SECRET=TWFwPFN0cmluZywgT2JqZWN0PiBjbGFpbXMgPSBuZXcgSGFzaE1hcDw+KCk7CmNsYWltcy5wdXQoImEiICwgMSk7CmNsYWltcy5wdXQoImIiICwgMik7Cg==
    networks:
      - mynet
    depends_on:
      - ecommerce-rmq

  shipping-service:
    image: ecommerce-saga-poc/shipping-service
    ports:
      - "8087:8087"
    environment:
      - SERVER_PORT=8087
      - MQ_USERNAME=guest
      - MQ_PASSWORD=guest
      - MQ_HOST=ecommerce-rmq
      - MQ_VHOST=/
      - MQ_PORT=5672
      - GATEWAY_URL=http://gateway-service:8000
      - JWT_SECRET=TWFwPFN0cmluZywgT2JqZWN0PiBjbGFpbXMgPSBuZXcgSGFzaE1hcDw+KCk7CmNsYWltcy5wdXQoImEiICwgMSk7CmNsYWltcy5wdXQoImIiICwgMik7Cg==
    networks:
      - mynet
    depends_on:
      - ecommerce-rmq

networks:
  mynet:
    driver: bridge








